# Generated by Django 3.0.2 on 2020-01-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='available',
            field=models.BooleanField(verbose_name='В наличии'),
        ),
    ]
