# Generated by Django 3.0.2 on 2020-01-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200122_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='img',
            field=models.ImageField(default=1, upload_to='static/img/food/tags/', verbose_name='Изображение: '),
            preserve_default=False,
        ),
    ]
