# Generated by Django 3.0.2 on 2020-01-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_tag_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='slug',
            new_name='slug_dish',
        ),
        migrations.RenameField(
            model_name='dishcategory',
            old_name='slug',
            new_name='slug_dishcategory',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='slug',
            new_name='slug_restaurant',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='slug',
            new_name='slug_tag',
        ),
    ]
