# Generated by Django 3.0.2 on 2020-01-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='time_delivery',
            field=models.IntegerField(verbose_name='Время доставки: '),
        ),
    ]
