# Generated by Django 3.0.2 on 2020-01-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200122_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='DishCategory',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
